In [3]:
import numpy as np
# Example: Creating a 1D, 2D, and 3D NumPy array
arr_1d = np.array([1, 2, 3, 4])
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])  # 2D Array (3x2)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D Array (2x2x2)

print("1D Array:\n", arr_1d)
print("2D Array:\n", arr_2d)
print("3D Array:\n", arr_3d)


1D Array:
 [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]
 [5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1], [2]], [[3], [4]]])

print(arr_1d.ndim)  # Output: 1 (1D)
print(arr_2d.ndim)  # Output: 2 (2D)
print(arr_3d.ndim)  # Output: 3 (3D)
import numpy as np

1
2
3
