In [3]:
#Initialize NumPy Arrays
# 2D Array with zeros
import numpy as np
arr_zeros = np.zeros((3, 3))  # 3x3 zeros matrix
print(arr_zeros)

# 2D Array with ones
arr_ones = np.ones((2, 4))  # 2x4 ones matrix
print(arr_ones)

# Full matrix with constant value
arr_full = np.full((2, 2), 7)  # 2x2 matrix filled with 7
print(arr_full)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
