In [3]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
joined_arr_1d = np.concatenate((arr1, arr2))
print("array 1:", arr1)
print("array 2:", arr2)
print("joined array:", joined_arr_1d)

array 1: [1 2]
array 2: [3 4]
joined array: [1 2 3 4]


In [4]:
arr3d_1 = np.array([[[1, 2]], [[3, 4]]])
arr3d_2 = np.array([[[5, 6]], [[7, 8]]])
joined_arr_3d = np.concatenate((arr3d_1, arr3d_2), axis=0)
print(joined_arr_3d)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]
