In [1]:

#Reshape a NumPy Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr_2d = arr.reshape(2, 3)  # Reshaping to 2x3 matrix
reshaped_arr_3d = arr.reshape(2, 1, 3)  # Reshaping to 2x1x3 matrix
print(reshaped_arr_2d)
print(reshaped_arr_3d)


[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]
